version: '3.3'

services:
  web:
    build: devops_challenge_app
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./devops_challenge_app/django_celery:/devops_challenge_app
    ports:
      - 8000:8000 
    depends_on:
      - redis
  
  celery:
    build: ./devops_challenge_app
    command:  python -m celery -A django_celery worker 
    volumes:
      - ./devops_challenge_app:/devops_challenge_app
    depends_on: 
      - web
      - redis

  redis:
    image: redis
    