apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minikube-ingress
spec:
  rules:
  - host: minikube.local
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
             name: devops-challenge-web-service
             port: 
              number: 8000